services:
  - type: web
    name: vegaai-service
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirement.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
